### PR TITLE
Comm calls init for you if that's already happened

### PR DESCRIPTION
**Pull request by ahmadia**
@cekees - Any reason not to merge this?

### CODE REVIEW

**Comment by cekees** [comment]
Seems OK to me. Should we warn that init hadn't been called?

**Comment by ahmadia** [comment]
No, because this object is self-instantiating.  I don't see an explicit reason right now to force the user to know whether init has been called or not.

**Comment by ahmadia** [comment]
Sorry, I misunderstood.  Yes, let's log this if it occurs.

**Comment by ahmadia** [comment]
I'm a little concerned about the order of events with the `Profiling.logEvent` function, and that if you try to call it before the profiler has been set up, I believe it hard crashes.  For now I'm not going to add the log functionality here, but I'll raise an issue related to this.

**Comment by ahmadia** [comment]
Ooph, I need another cup of coffee.  That function looks safe to me.  I'll open a new PR.

**Pull request merged**
