### PR TITLE
equalsNone2isNone_patch

### PR DESCRIPTION
**Pull request by zhang-alvin**
Associated with Issue #562.

This PR is a patch that substitutes all instances of `== None` and `!= None` with `is None` and `is not None`, respectively. This is done to hopefully avoid any further issues like that seen in PR #559.

### CODE REVIEW

**Comment by alistairbntl** [comment]
@zhang-alvin - I think this looks good.  
Has this been tested this against anything in the `air-water-vv` repo?  If not I think it would be a good sanity check before merging.  @lmaurel - perhaps you could run this branch against some of you tests to verify that everything is kosher (keep in mind this does not include patch #564.)

**Comment by zhang-alvin** [comment]
Good call on sanity checks @alistairbntl. I ran both the dambreak_Colagrossi case and compared it with the results acquired prior to the modifications associated with this PR (same mesh):

dambreakcolagrossi_beforeandafterpr

I'll try a slightly more complicated case like the floating bar case just in case.

**Comment by lmaurel** [comment]
@zhang-alvin @alistairbntl I ran my tests on this branch and the results are fine for me.

**Comment by alistairbntl** [comment]
@lmaurel - Thanks for running that.  I think this is good to go!

**Pull request merged**
