### PR TITLE
Copper/update

### PR DESCRIPTION
**Pull request by adimako**
@cekees, this is the version I used for running the cases. As said only some tweaks in WaveTools

### CODE REVIEW

**Comment by adimako** [comment]
Also do not merge, it is not there yet

**Comment by adimako** [comment]
@cekees Failed because of memory access errors, but compiles ok in copper

**Comment by adimako** [comment]
Synchonised flcbdWrappers with the master branch, same profile results

**Comment by cekees** [comment]
Is this ready to merge too? Or  is it  out of date since the other branch went into stable/copper?

**Comment by adimako** [comment]
@cekees, this is stale, should be removed. I have implemented these already in WaveTools

**Pull request closed without merging**
