### PR TITLE
Update dev

### PR DESCRIPTION
**Pull request by cekees**
- switch to MIT license in LICENSE.md and use approach advocated by defense digital service
- adds CONTRIBUTORS.md for listing developers and copyrights for those who can claim copyrights
- adds CONTRIBUTING.md to give basic guidance on how to make a contribution
- adds RELEASE.md to explain how to setup a release commit on master and switch back to a dev branch
- cleans up some old email references
- adds binder badge for starting jupyerhub instance on master from README
- cleans up profling message that has been getting printed everytime you run something with proteus.Profiling.

### CODE REVIEW

**Comment by cekees** [comment]
Thanks @adimako . @alistairbntl and @zhang-alvin we need your to add your copyright.

**Comment by cekees** [comment]
@nehaljwani Could you go ahead and add a copyright statement for your or continuum after verifying how continuum wants to handle your contributions with @msarahan? I know the plan we discussed was for me or one of our developers to submit patches fixing what you need, but I was offline all day yesterday so missed the discussion and merge of your PR by @alistairbntl . @alistairbntl from here on don't merge PR's for contributors who haven't signed on. DDS is building webhooks that will automate some of this, but it may be a while before it's automated on the proteus repo.

**Comment by alistairbntl** [comment]
@cekees - Opps, I didn't consider this.  I think we can still undue the merge if it's going to create a problem.

**Comment by cekees** [comment]
No problem. Let's just see if we can add @nehaljwani as a contributor as this is probably not the last thing he'll hit trying to create a conda package for proteus.

**Comment by cekees** [comment]
If that doesn't work we'll undo the merge.

**Pull request merged**
