### PR TITLE
MeshAdaptPUMI/ErrorResidualMethod: avoid dynamic arrays.

### PR DESCRIPTION
**Pull request by tjcorona**
Set the array length for simplex iteration to 4, its maximum value.

### CODE REVIEW

**Comment by zhang-alvin** [comment]
Thanks for finding this. The underlying issue causing the check to fail is because the LHS matrix K and the RHS vector F is uninitialized, so with 2D cases the behavior is erratic. This can be fixed by initializing K and F to zero by replacing the following [lines](https://github.com/tjcorona/proteus/blob/fix-isInSimplex/proteus/MeshAdaptPUMI/ErrorResidualMethod.cpp#L152-L153) with 

```
  apf::Matrix3x3 K(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0);
  apf::Matrix3x3 Kinv;
  apf::Vector3 F(0.0,0.0,0.0);
 ```

**Comment by tjcorona** [comment]
The issue I was fixing had to do with erroneously dynamically allocating c-style arrays of non-POD datatypes. The changes I made allowed me to compile the code; it looks like your fixes are necessary for the method to run correctly.

**Comment by zhang-alvin** [comment]
If it's alright with you, I'm just going to directly add the fixes to your branch and then merge the pull-request.

**Comment by tjcorona** [comment]
That sounds great. Thanks!

**Comment by alistairbntl** [comment]
@zhang-alvin - I just noticed that the tests are failing on this branch which was merged into master.  If there is just a single test that is failing could you possibly add a `skip` flag so that tests pass?

**Comment by zhang-alvin** [comment]
@alistairbntl Thanks for pointing this out. Looking at the [master Travis build](https://travis-ci.org/erdc-cm/proteus/builds/230815958) post-merge, things look fine. The cause of the failure of the tests for this PR seem to be related to [closing a pull request](https://github.com/travis-ci/travis-ci/issues/5693).

**Comment by alistairbntl** [comment]
@zhang-alvin - Agreed, everything looks good with the PR.  Thanks for pointing this out.  @cekees - I see that the `main` proteus branch has a failed test related to the docker image.  Are you aware of this?

**Pull request merged**
