### PR TITLE
added  options and tweaked fixed step algorithms

### PR DESCRIPTION
**Pull request by cekees**
This allows setting a system-wide fixed step in three ways
1) just use the tnList and ignore everything else (Sequential_FixedStep_Simple)
2) use so.dt_system_fixed and ignore tnList (Sequential FixedStep with so.stepExactSystem=False)
3) use so.dt_system_fixed and so.stepExactSystem=True (Sequential_FixedStep)

@tridelat I think you want option 2 or 3, the only difference being whether the archive contains exactly the steps in tnList or just the first step after each time in tnList. The latter ensures that all numerical steps are exactly dt_system. @manuel-quezada and @alistairbntl you may find mode 3 useful for convergence studies. 

todo
- [x] write some simple regressions tests using ADR equation
- [x] add some documentation

### CODE REVIEW

**Comment by cekees** [comment]
moving these changes onto add_rans3p

**Comment by tridelat** [comment]
@cekees, the changes for fixed time steps have not been merged into master, was it intentional (or will add_rans3p be merged to master soon)? 
#465 contains the changes without the other commits (it was merged into this branch, not master)

**Comment by cekees** [comment]
Yes, unless you need the functionality right away, I'll just merge add_rans3p in the next day or two since it contains these commits.

**Comment by tridelat** [comment]
No problem, I am using it by merging the branch right now so it can wait to be in master.

**Pull request closed without merging**
