### PR TITLE
Restructured Proteus notebooks directory.

### PR DESCRIPTION
**Pull request by alistairbntl**

### CODE REVIEW

**Comment by alistairbntl** [comment]
@cekees , @adimako  and any other interested parties, would you mind pulling the PR and checking that the links all work correctly?  They seem to work okay on my machine but it would be nice to double check.
Also in the applications could somebody add a brief description of the 2D tank problem!  Thanks.

**Comment by alistairbntl** [comment]
@cekees , @adimako  - do y'all think this is ready to go?

**Comment by cekees** [comment]
Yes, fine by me. I added  #493 on collecting notebook utilities from the notebook directory tree in some future PR.

**Comment by cekees** [comment]
Sorry, meant to get you that description. "This notebook provides a numerical model (2D vertical slide) of an experimental wave tank"

**Pull request merged**
