### PR TITLE
Tank2D with Obstacles - new class for air-water-vv refactoring support

### PR DESCRIPTION
**Pull request by nerisaurus**
This class allows for a simple way to build most air-water-vv style problems where a mostly rectangular tank has obstacles (such as a weir, a sloped bottom, etc.).  The implementation is a bit messy and a more in depth gmsh interface should handle this eventually.  It extends off of the refactored Tank2D.

(a new pull request to bring it directly to master, since Tank2D resolved first and github doesn't have transitive pull requests)

### CODE REVIEW

**Comment by cekees** [comment]
Could you post an example of the usage? You could link to where you use this in air-water-vv or link to a gist containing a script that builds a non-trivial domain and plots it.

**Comment by nerisaurus** [comment]
[Here's](https://github.com/erdc-cm/air-water-vv/tree/nneri/refactor/constantSlopeBeach/2d/constantSlopeBeach/Mase_and_Kirby_shoaling) an example from the `constantSlopeBeach` set.  All hydraulicStructure ([in this PR](https://github.com/erdc-cm/air-water-vv/pull/125)) and constantSlopeBeach tests ([in this PR](https://github.com/erdc-cm/air-water-vv/pull/122)) use this, so you can look around at them for other uses.

**Comment by cekees** [comment]
Just to clarify: obstacles boundaries must intersect the tank boundary?

**Comment by nerisaurus** [comment]
Yes.  A ValueError is raised if they do not. Other obstacles can still be included via additional shapes.

**Pull request merged**
