### PR TITLE
Weighted relaxation function

### PR DESCRIPTION
**Pull request by adimako**
@cekees @tridelat @Giovanni-Cozzuto-1989. We had been going through this a while ago, and since I am completing WaveTools report, I thought it would be nice to check the effect of the RZ function (H_s) to coefficients.

I checked the following curves

### CODE REVIEW

**Comment by adimako** [comment]
capture

**Comment by adimako** [comment]
Blue dashed is the exponential distro that eleni used which performed decently. The sinfunction is the new one that it is a bit like the smoothed heavinside and the weighted one is a combination of the two. Turns out ("surprise - suprise") that the weighted one is the best, as it has a smooth transition at the beginning to avoid non-physical effects and then it matches the exponential.

**Comment by adimako** [comment]
I think it is reasonable to use the weighted one from now on. Also I will post the flume cases for using them in regression tests. Such tests will be really useful for doing such an analysis

**Comment by cekees** [comment]
I'm not sure why the tests are failing now, given that this is a small change. I'm relaunched the tests just to see if it was some sort of a load issue on travis.

**Comment by cekees** [comment]
Thanks! @nerisaurus the tests mentioned here might be good  for you to look at it when they go up on air-water-vv.

**Comment by adimako** [comment]
@cekees, this branch compiles in copper so I think it should be ok merging it. 
@nerisaurus, I have created a branch in air water-vv where you can find these tests (and other tests as well). Feel free to review and recommend changes to the structures.

**Comment by adimako** [comment]
Merging this one

**Pull request merged**
