### PR TITLE
Fixed leaks - cherry pick from hydra/stable

### PR DESCRIPTION
**Pull request by adimako**
The leaks are fixed. I was doing something naive: starting new pointers within the C++ scope, which turns out that it is too troublesome to deallocate. 

Now the velocity is passed as a pointer through the argument list and it is updated within the function, therefore all _cpp_u functions are treated as void.

I will do one minor optimisation yet and then hopefully we merge and resolve this Bug

### CODE REVIEW

**Comment by adimako** [comment]
@Giovanni-Cozzuto-1989 @cekees @tridelat. This will resolve the memory leaks + reduce some calls to cosh for imrpoving speed. I do not know why it fails, I get an error saying that the log is too big?

**Comment by cekees** [comment]
Can you paste in the error message about the log being too big?

**Comment by adimako** [comment]
`The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
The job has been terminated`

It did not fail for this though, a conflict caused it

**Comment by cekees** [comment]
I think that's referring to the py.test log. Might want to check if there
is a print statement left inside a loop somewhere.

**Comment by adimako** [comment]
Indeed, I have a print statement for printing some error values, should I remove it

**Pull request merged**
